# Generated by Django 5.2 on 2025-09-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_userprofile_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='roll_no',
            field=models.CharField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
