# Generated by Django 5.1.7 on 2025-10-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_alter_notification_options_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='interaction_status',
            field=models.CharField(choices=[('idle', 'Idle (Ready to scan ID)'), ('scanned', 'ID Scanned (Awaiting medicine choice)'), ('requested', 'Medicine Requested (Awaiting dispense confirmation)')], default='idle', help_text='Current interaction state with the IoT box.', max_length=20),
        ),
    ]
