# Generated by Django 5.2 on 2025-10-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_userprofile_interaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemstatus',
            name='camera_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemstatus',
            name='camera_on',
            field=models.BooleanField(default=False),
        ),
    ]
