# Generated by Django 5.2 on 2025-11-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0008_remove_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='face_encoding_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
