# Generated by Django 5.2 on 2025-11-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0009_userprofile_face_encoding_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='face_encoding_path',
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('low_stock', 'Low Stock'), ('expired', 'Expired Medicine'), ('system_alert', 'System Alert'), ('success', 'Success'), ('error', 'Error'), ('alert', 'Alert')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='interaction_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('scanned', 'ID Scanned'), ('requested', 'Medicine Requested'), ('pending_scan', 'Pending Scan')], default='idle', max_length=20),
        ),
    ]
